using System;

namespace Dangl.WebDocumentation.Services
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "0.1.164";
        public static string CommitInfo => "Branch.master.Sha.a8716d64b04658658a32eb8beca6555c0a1e9983";
        public static string CommitDate => "2018-12-30";
        public static string CommitHash => "a8716d64b04658658a32eb8beca6555c0a1e9983";
        public static string InformationalVersion => "0.1.164+Branch.master.Sha.a8716d64b04658658a32eb8beca6555c0a1e9983";
        public static DateTime BuildDateUtc { get; } = new DateTime(2018, 12, 30, 16, 45, 13, DateTimeKind.Utc);
    }
}